/* ruetLateX — app : live binding, tap-to-edit, windowless autofit, print = PDF */
(function(){
  const $ = (s, r=document)=>r.querySelector(s);
  const $$ = (s, r=document)=>[...r.querySelectorAll(s)];
  const sheet = $('#sheet'), stage = $('#stage'), scaler = $('#scaler');

  // tiny toast for feedback (no statusbar anymore)
  let toastEl = null, toastT = null;
  function flash(msg){
    if(!toastEl){
      toastEl = document.createElement('div');
      toastEl.style.cssText = 'position:fixed;bottom:18px;left:50%;transform:translateX(-50%);background:#111827;color:#fff;font-size:13px;font-weight:600;padding:9px 16px;border-radius:10px;z-index:200;opacity:0;transition:opacity .2s;pointer-events:none;max-width:90vw;text-align:center';
      document.body.appendChild(toastEl);
    }
    toastEl.textContent = msg;
    toastEl.style.opacity = '1';
    clearTimeout(toastT);
    toastT = setTimeout(()=>{ toastEl.style.opacity = '0'; }, 2400);
  }

  const state = {};
  function collect(){
    $$('[data-bind]').forEach(el=>{ state[el.dataset.bind] = el.value; });
    state.expLabel = state.expLabel || 'Experiment';
  }
  const map = {
    moto:'v-moto', dept:'v-dept', univ:'v-univ', reportHead:'v-reportHead',
    courseCode:'v-courseCode', courseTitle:'v-courseTitle',
    expLabel:'v-expLabel', expNo:'v-expNo', expTitle:'v-expTitle',
    byLabel:'v-byLabel', student:'v-student', roll:'v-roll', session:'v-session',
    toLabel:'v-toLabel', teacher:'v-teacher', desig:'v-desig', tdept:'v-tdept',
    dateExpLabel:'v-dateExpLabel', dateExp:'v-dateExp',
    dateSubLabel:'v-dateSubLabel', dateSub:'v-dateSub',
    rwTitle:'v-rwTitle', vivaTitle:'v-vivaTitle', teacherSec:'v-teacherSec', signCap:'v-signCap'
  };

  function texEscape(s){return String(s??'').replace(/\\/g,'\\textbackslash{}').replace(/&/g,'\\&').replace(/%/g,'\\%').replace(/\$/g,'\\$').replace(/#/g,'\\#').replace(/_/g,'\\_').replace(/{/g,'\\{').replace(/}/g,'\\}').replace(/\^/g,'\\textasciicircum{}').replace(/~/g,'\\textasciitilde{}');}

  // stored rich-text per field: key -> {plain, html}. Survives re-renders;
  // cleared automatically when the sidebar input text changes.
  const fmtState = {};
  const revMap = Object.fromEntries(Object.entries(map).map(([k,id])=>[id,k]));

  function render(){
    collect();
    for(const [k,id] of Object.entries(map)){
      const el = document.getElementById(id);
      if(!el) continue;
      const f = fmtState[k];
      if(f && state[k] === f.plain){
        if(el.innerHTML !== f.html) el.innerHTML = f.html;
      } else {
        el.textContent = state[k];
        delete fmtState[k];
      }
    }
    buildTex();
  }

  const defaults = {
    moto:"Heaven's Light is Our Guide", dept:"Department of Electronics & Telecommunication Engineering",
    univ:"Rajshahi University of Engineering & Technology", reportHead:"Laboratory Report on",
    courseCode:"ETE XXXX", courseTitle:"Sessional Based on ETE XXXX",
    expLabel:"Experiment", expNo:"01",
    expTitle:"Experimental Study of Low Pass Filter, High Pass Filter, Band Pass Filter and Band Stop Filter Using MATLAB Simulink.",
    byLabel:"Submitted by:", student:"Donald Trump", roll:"Roll No. 24040XX", session:"Session: 20XX-XX",
    toLabel:"Submitted to:", teacher:"Teacher's Name", desig:"Assistant Professor", tdept:"Dept. of ETE, RUET",
    dateExpLabel:"Date of Experiment :", dateExp:"04/08/2026", dateSubLabel:"Date of Submission :", dateSub:"11/08/2026",
    rwTitle:"Report Writing", vivaTitle:"Lab Viva", teacherSec:"(Teacher's Section)", signCap:"Signature"
  };

  function buildTex(){
    const v = k => texEscape(state[k] ?? defaults[k] ?? '');
    const expNum = (state.expNo||'01').trim();
    const logoMm = parseFloat(($('#logoPos')||{}).value || '0') || 0;
    const logoShift = logoMm ? `\\hspace*{${(logoMm/10).toFixed(1)}cm}` : '';
    const tex = `% ========================================================================
% RUET LAB COVER — generated by ruetLateX
% Compile with pdfLaTeX on Overleaf. Place ruet_logo.png beside this file.
% ========================================================================
\\documentclass[a4paper,12pt]{report}
\\usepackage[utf8]{inputenc}
\\usepackage{fourier}
\\usepackage{graphicx}
\\usepackage[top=1in, bottom=1in, left=1.2in, right=1in]{geometry}
\\usepackage{multicol}
\\usepackage{enumitem}
\\usepackage{xcolor}
\\usepackage{titlesec}
\\usepackage{tocloft}
\\usepackage{sectsty}
\\usepackage{setspace}
\\usepackage{fancyhdr}
\\linespread{1.25}
\\setlength{\\columnseprule}{0pt}
\\NewDocumentCommand{\\myrule}{O{1pt} O{2pt} O{black}}{\\par\\nobreak\\kern\\the\\prevdepth\\kern#2{\\color{#3}\\hrule height #1 width\\hsize}\\kern#2\\nointerlineskip}
\\renewcommand{\\chaptername}{${v('expLabel')}}
\\titleformat{\\chapter}[display]{\\centering\\Large\\bfseries}{\\chaptertitlename\\ \\thechapter}{0pt}{\\large}
\\titlespacing*{\\chapter}{0pt}{-8pt}{0pt}
\\newcommand{\\Moto}{${v('moto')}}
\\newcommand{\\Dept}{${v('dept')}}
\\newcommand{\\University}{${v('univ')}}
\\newcommand{\\CourseCode}{${v('courseCode')}}
\\newcommand{\\CourseTitle}{${v('courseTitle')}}
\\pagestyle{empty}
\\begin{document}
\\thispagestyle{empty}
\\begin{center}
{\\small \\textit{\\Moto}} \\\\[0.5pc]
\\centerline{${logoShift}\\includegraphics[width=${$('#logoWidth').value}cm]{ruet_logo.png}}
\\vspace{0.2cm}
{\\large \\textbf{\\Dept}} \\\\
{\\large \\textbf{\\University}} \\\\[0.5cm]
\\textbf{\\Large ${v('reportHead')}} \\\\[0.2cm]
\\textbf{\\large \\CourseCode} \\textbf{\\large (\\CourseTitle)} \\\\[0.8cm]
\\myrule[1pt][5pt]
\\begin{minipage}{\\textwidth}
\\setcounter{chapter}{${/^\d+$/.test(expNum)?expNum:'01'}}
\\chapter{${v('expTitle')}}
\\end{minipage}
\\vspace{0.2cm}
\\thispagestyle{empty}
\\myrule[1pt][5pt]
\\vspace{0.5cm}
\\noindent
\\begin{minipage}[t]{0.46\\linewidth}
\\begin{flushleft}
\\normalsize \\emph{\\textbf{${v('byLabel')}}}\\\\
${v('student')}\\\\
${v('roll')}\\\\
${v('session')}
\\end{flushleft}
\\end{minipage}\\hspace*{0.002\\linewidth}
\\begin{minipage}[t]{0.46\\linewidth}
\\begin{flushright}
\\normalsize \\emph{\\textbf{${v('toLabel')}}}\\\\
${v('teacher')}\\\\
${v('desig')}\\\\
${v('tdept')}
\\end{flushright}
\\end{minipage}
\\vspace{0.5cm}
\\textbf{${v('dateExpLabel')} ${v('dateExp')}} \\\\
\\textbf{${v('dateSubLabel')} ${v('dateSub')}}
\\vspace{4cm}
\\hrulefill
\\vspace{0.2cm}
\\begin{multicols}{3}
\\textbf{\\underline{${v('rwTitle')}}}
\\begin{itemize}[labelindent=3em, labelsep=0.5cm, leftmargin=*, noitemsep]
\\item[$\\square$] Excellent
\\item[$\\square$] Good
\\item[$\\square$] Average
${$('#showPoor').checked?'\\item[$\\square$] Poor':''}
\\end{itemize}
\\columnbreak
\\textbf{${v('teacherSec')}} \\\\
\\vspace{1.5cm}
\\hrulefill \\\\
${v('signCap')}
\\columnbreak
\\textbf{\\underline{${v('vivaTitle')}}}
\\begin{itemize}[labelindent=3em, labelsep=0.5cm, leftmargin=*, noitemsep]
\\item[$\\square$] Excellent
\\item[$\\square$] Good
\\item[$\\square$] Average
${$('#showPoor').checked?'\\item[$\\square$] Poor':''}
\\end{itemize}
\\end{multicols}
\\vspace{1cm}
\\end{center}
\\end{document}`;
    $('#texCode').textContent = tex;
  }

  // ---- tap to edit switch + Word-style floating format toolbar ----
  // two switches (desktop in-menu + compact in mobile bar) share one state
  const tapToggle = $('#tapEditToggle');
  const tapToggleM = $('#tapEditToggleMobile');
  const tapToggles = [tapToggle, tapToggleM].filter(Boolean);
  tapToggles.forEach(t => { t.checked = false; });
  function isTapOn(){ return !!(tapToggle && tapToggle.checked); }
  function applyTap(){
    const on = isTapOn();
    tapToggles.forEach(t => {
      t.classList.toggle('on', on);
      t.setAttribute('aria-checked', String(on));
      if(t !== tapToggle) t.checked = on;
    });
    syncTap();
  }
  function syncTap(){
    const on = isTapOn();
    sheet.classList.toggle('tap-on', on);
    const editable = $$('#sheet [data-field], #sheet .marks li');
    editable.forEach(el=>{ el.contentEditable = on ? 'true' : 'false'; el.spellcheck = false; });
    if(!on) hideToolbar();
  }
  tapToggles.forEach(t => t.addEventListener('click', ()=>{
    tapToggle.checked = !isTapOn();
    if(t !== tapToggle) t.checked = tapToggle.checked;
    applyTap();
    saveSoon();
  }));

  // ---- marking table editor : collapsed by default, toggle reveals the boxes ----
  const markingToggle = $('#markingToggle'), markingFields = $('#markingFields');
  markingToggle.checked = false;
  function applyMarking(){
    const on = !!markingToggle.checked;
    markingToggle.classList.toggle('on', on);
    markingToggle.setAttribute('aria-checked', String(on));
    markingFields.hidden = !on;
  }
  markingToggle.addEventListener('click', ()=>{
    markingToggle.checked = !markingToggle.checked;
    applyMarking();
    saveSoon();
  });

  // key owning a node inside the sheet (prefers the v-* target, falls back to wrapper)
  function keyFromNode(node){
    const n = node && node.nodeType === 3 ? node.parentElement : node;
    if(!n || !sheet.contains(n)) return null;
    const t = n.closest ? n.closest('[id^="v-"]') : null;
    if(t && revMap[t.id]) return revMap[t.id];
    const f = n.closest ? n.closest('[data-field]') : null;
    return f ? keyForPreview(f) : null;
  }
  function saveFmtFromSelection(){
    const sel = window.getSelection();
    if(!sel.rangeCount) return;
    const k = keyFromNode(sel.anchorNode);
    if(!k) return;
    const target = document.getElementById(map[k]);
    if(!target) return;
    fmtState[k] = { plain: target.textContent, html: target.innerHTML };
  }

  // floating toolbar (built once)
  const toolbar = document.createElement('div');
  toolbar.id = 'fmtToolbar';
  toolbar.setAttribute('role', 'toolbar');
  toolbar.setAttribute('aria-label', 'Text formatting');
  toolbar.innerHTML =
    '<button type="button" data-cmd="bold" title="Bold"><b>B</b></button>' +
    '<button type="button" data-cmd="italic" title="Italic"><i>I</i></button>' +
    '<button type="button" data-cmd="underline" title="Underline"><u>U</u></button>' +
    '<button type="button" data-cmd="strikeThrough" title="Strikethrough"><s>S</s></button>' +
    '<span class="sep"></span>' +
    '<button type="button" data-cmd="superscript" title="Superscript">x<sup>2</sup></button>' +
    '<button type="button" data-cmd="subscript" title="Subscript">x<sub>2</sub></button>' +
    '<span class="sep"></span>' +
    '<button type="button" id="fmtDec" title="Decrease font size">A&minus;</button>' +
    '<button type="button" id="fmtInc" title="Increase font size">A+</button>' +
    '<span class="sep"></span>' +
    '<button type="button" data-cmd="removeFormat" title="Clear formatting">&#x2715;</button>';
  document.body.appendChild(toolbar);
  function hideToolbar(){ toolbar.classList.remove('show'); }
  function positionToolbar(){
    const sel = window.getSelection();
    if(!isTapOn() || !sel.rangeCount || sel.isCollapsed) return hideToolbar();
    const r = sel.getRangeAt(0);
    if(!sheet.contains(r.commonAncestorContainer)) return hideToolbar();
    const rect = r.getBoundingClientRect();
    if(!rect || (rect.width === 0 && rect.height === 0)) return hideToolbar();
    toolbar.classList.add('show');
    const tw = toolbar.offsetWidth || 300, th = toolbar.offsetHeight || 40;
    let x = rect.left + rect.width / 2 - tw / 2;
    x = Math.min(Math.max(8, x), window.innerWidth - tw - 8);
    let y = rect.top - th - 10;
    if(y < 70) y = rect.bottom + 10; // below selection when nav is in the way
    toolbar.style.left = x + 'px';
    toolbar.style.top = y + 'px';
  }
  // keep selection alive while pressing toolbar buttons
  toolbar.addEventListener('mousedown', (e)=>{ e.preventDefault(); });
  toolbar.addEventListener('click', (e)=>{
    const btn = e.target.closest('button');
    if(!btn) return;
    if(btn.id === 'fmtInc' || btn.id === 'fmtDec'){
      changeSelSize(btn.id === 'fmtInc' ? 1 : -1);
    } else {
      document.execCommand(btn.dataset.cmd, false, null);
      saveFmtFromSelection();
    }
    positionToolbar();
  });
  function changeSelSize(dir){
    const sel = window.getSelection();
    if(!sel.rangeCount || sel.isCollapsed) return;
    const range = sel.getRangeAt(0);
    if(!sheet.contains(range.commonAncestorContainer)) return;
    const host = sel.anchorNode && sel.anchorNode.nodeType === 3 ? sel.anchorNode.parentElement : sel.anchorNode;
    const cur = parseFloat(host && host.getBoundingClientRect ? getComputedStyle(host).fontSize : '16') || 16;
    const el = document.createElement('span');
    el.style.fontSize = Math.max(8, Math.round(cur + dir * 2)) + 'px';
    try { range.surroundContents(el); }
    catch { el.appendChild(range.extractContents()); range.insertNode(el); }
    sel.selectAllChildren(el);
    saveFmtFromSelection();
  }
  let selQueued = false;
  document.addEventListener('selectionchange', ()=>{
    if(selQueued) return;
    selQueued = true;
    requestAnimationFrame(()=>{ selQueued = false; positionToolbar(); });
  });
  sheet.addEventListener('mouseup', ()=>{ setTimeout(positionToolbar, 0); });
  window.addEventListener('scroll', hideToolbar, true);

  function flashInput(key){
    // NOTE: never steals focus — the caret must stay in the preview so typing works.
    // We only scroll the sidebar to the field and highlight it.
    const inp = $(`[data-bind="${key}"]`);
    if(!inp) return;
    const card = inp.closest('details');
    if(card && !card.open) card.open = true;
    inp.scrollIntoView({behavior:'smooth', block:'center'});
    inp.classList.add('field-flash');
    setTimeout(()=>inp.classList.remove('field-flash'), 1400);
  }
  function keyForPreview(el){
    const f = el.closest('[data-field]');
    if(!f) return null;
    const key = f.dataset.field;
    if(key==='courseCode') return 'courseCode';
    if(key==='logo') return null;
    if(map[key]) return key;
    const inner = f.querySelector('[id^="v-"]');
    if(inner){ for(const [k,id] of Object.entries(map)) if(id===inner.id) return k; }
    return key;
  }
  $$('#sheet [data-field]').forEach(el=>{
    el.addEventListener('click', ()=>{
      if(!isTapOn()) return;
      const sel = window.getSelection();
      if(sel && !sel.isCollapsed && sheet.contains(sel.anchorNode)) return; // user is selecting text
      const k = keyForPreview(el);
      if(k) flashInput(k);
      else if(el.dataset.field==='logo'){ $('#logoWidth').scrollIntoView({behavior:'smooth',block:'center'}); }
    });
    // typing straight in the preview syncs back to the sidebar (plain text) and keeps formatting
    el.addEventListener('input', ()=>{
      const k = keyFromNode(el);
      if(!k) return;
      const target = document.getElementById(map[k]);
      if(!target) return;
      const inp = $(`[data-bind="${k}"]`);
      if(inp) inp.value = target.textContent;
      fmtState[k] = { plain: target.textContent, html: target.innerHTML };
    });
    // Enter finishes editing instead of splitting the line; paste as plain text
    el.addEventListener('keydown', (ev)=>{
      if(ev.key==='Enter'){ ev.preventDefault(); el.blur(); }
    });
    el.addEventListener('paste', (ev)=>{
      ev.preventDefault();
      const text = (ev.clipboardData || window.clipboardData).getData('text/plain');
      document.execCommand('insertText', false, text);
    });
  });
  // marking checkboxes have no sidebar field — keep them typable with clean Enter/paste
  $$('#sheet .marks li').forEach(el=>{
    el.addEventListener('keydown', (ev)=>{
      if(ev.key==='Enter'){ ev.preventDefault(); el.blur(); }
    });
    el.addEventListener('paste', (ev)=>{
      ev.preventDefault();
      const text = (ev.clipboardData || window.clipboardData).getData('text/plain');
      document.execCommand('insertText', false, text);
    });
  });
  syncTap();

  // ---- fonts : custom inputs visible ONLY when "Custom Google Font…" is picked ----
  const fontSelect = $('#fontSelect');
  const customWrap = $('#customFontWrap');
  let customFamily = null;
  function applyFontValue(val){
    if(val === 'custom'){
      customWrap.hidden = false;
      if(customFamily) sheet.style.fontFamily = `'${customFamily}', serif`;
      return;
    }
    customWrap.hidden = true;
    sheet.style.fontFamily = val;
  }
  fontSelect.addEventListener('change', ()=>{
    applyFontValue(fontSelect.value);
    if(fontSelect.value !== 'custom') flash('Font: ' + fontSelect.selectedOptions[0].textContent);
    requestAnimationFrame(updateScale);
  });
  // ---- base size + line spacing : presets plus user-typed custom values ----
  const baseSizeSel = $('#baseSize'), baseSizeCustom = $('#baseSizeCustom');
  const lineSpacingSel = $('#lineSpacing'), lineSpacingCustom = $('#lineSpacingCustom');
  function applyBaseSize(){
    if(baseSizeSel.value === 'custom'){
      baseSizeCustom.hidden = false;
      const v = parseFloat(baseSizeCustom.value);
      if(v >= 8 && v <= 20) sheet.style.setProperty('--base-pt', v);
      return;
    }
    baseSizeCustom.hidden = true;
    sheet.style.setProperty('--base-pt', baseSizeSel.value);
    flash('Base size ' + baseSizeSel.value + 'pt');
  }
  function applyLineSpacing(){
    if(lineSpacingSel.value === 'custom'){
      lineSpacingCustom.hidden = false;
      const v = parseFloat(lineSpacingCustom.value);
      if(v >= 1 && v <= 3) sheet.style.setProperty('--leading', v);
      return;
    }
    lineSpacingCustom.hidden = true;
    sheet.style.setProperty('--leading', lineSpacingSel.value);
  }
  baseSizeSel.addEventListener('change', ()=>{ applyBaseSize(); requestAnimationFrame(updateScale); });
  lineSpacingSel.addEventListener('change', ()=>{ applyLineSpacing(); requestAnimationFrame(updateScale); });
  baseSizeCustom.addEventListener('input', ()=>{
    const v = parseFloat(baseSizeCustom.value);
    if(v >= 8 && v <= 20){
      sheet.style.setProperty('--base-pt', v);
      requestAnimationFrame(updateScale);
      saveSoon();
    }
  });
  lineSpacingCustom.addEventListener('input', ()=>{
    const v = parseFloat(lineSpacingCustom.value);
    if(v >= 1 && v <= 3){
      sheet.style.setProperty('--leading', v);
      requestAnimationFrame(updateScale);
      saveSoon();
    }
  });
  $('#gfontAdd').addEventListener('click', ()=>{
    const url = $('#gfontUrl').value.trim();
    const name = $('#gfontName').value.trim();
    if(!url || !name){ flash('Paste both URL and family name'); return; }
    let href = url;
    const m = url.match(/href="([^"]+)"/); if(m) href = m[1];
    if(!document.querySelector('link[data-gfont="' + name + '"]')){
      const l = document.createElement('link'); l.rel='stylesheet'; l.href=href; l.setAttribute('data-gfont', name); document.head.appendChild(l);
    }
    customFamily = name;
    // swap the "custom" option to this family so print keeps it
    const opt = fontSelect.querySelector('option[value="custom"]');
    opt.textContent = name + ' — custom (Google)';
    sheet.style.fontFamily = `'${name}', serif`;
    flash('Custom font "' + name + '" applied');
    requestAnimationFrame(updateScale);
  });

  // ---- layout controls ----
  $('#logoWidth').addEventListener('input', e=>{
    $('#v-logo').style.width = e.target.value + 'cm';
    $('#logoWidthVal').textContent = (+e.target.value).toFixed(1) + ' cm';
  });
  $('#logoPos').addEventListener('input', e=>{
    const mm = +e.target.value;
    $('#v-logo').style.transform = mm ? 'translateX(' + mm + 'mm)' : '';
    $('#logoPosVal').textContent = mm === 0 ? 'centered' : ((mm > 0 ? '+' : '') + mm + ' mm ' + (mm > 0 ? 'right' : 'left'));
  });
  $('#ruleThick').addEventListener('change', e=>{
    $$('#sheet .rule').forEach(r=>{ r.style.borderTopWidth = e.target.value + 'pt'; });
  });
  $('#ruleGap').addEventListener('change', e=>{
    const ch = $('.sheet .chapter');
    if(e.target.value==='compact'){ ch.style.padding = '1mm 0'; }
    else if(e.target.value==='wide'){ ch.style.padding = '4mm 0'; }
    else { ch.style.padding = ''; }
  });
  $('#showPoor').addEventListener('change', e=>{
    $$('#sheet .poor-row').forEach(r=>r.style.display = e.target.checked?'':'none');
    buildTex();
  });
  ['upperRule','lowerRule','bottomRule'].forEach((id)=>{
    document.getElementById(id).addEventListener('change', e=>{
      const show = e.target.checked;
      if(id==='upperRule') $('#ruleTop').style.display = show?'':'none';
      if(id==='lowerRule') $('#ruleBottom').style.display = show?'':'none';
      if(id==='bottomRule'){
        $('#ruleFooterWrap').style.borderTop = show ? '' : '0';
        $('#ruleFooterWrap').style.paddingTop = show ? '' : '0';
        $('#ruleFooterWrap').style.marginTop = show ? '' : '0';
      }
    });
  });
  // ---- teacher combobox : type-to-search RUET ETE faculty (fuzzy) ----
  const FACULTY = [
    { name: 'Dr. Md. Kamal Hosain', title: 'Professor' },
    { name: 'Dr Md Munjure Mowla', title: 'Professor' },
    { name: 'Dr. Mst. Fateha Samad', title: 'Professor' },
    { name: 'Dr. Shah Ariful Hoque Chowdhury', title: 'Professor' },
    { name: 'Dr. Tushar Kanti Roy', title: 'Associate Professor' },
    { name: 'Dr. Md Rabiul Hasan', title: 'Associate Professor' },
    { name: 'Abdulla Al Suman', title: 'Assistant Professor' },
    { name: 'JANNATUL ROBAIAT MOU', title: 'Assistant Professor' },
    { name: 'Sham Datto', title: 'Assistant Professor' },
    { name: 'Md. Aslam Mollah', title: 'Assistant Professor' },
    { name: 'A. S. M. Badrudduza', title: 'Assistant Professor' },
    { name: 'Dr. Md. Yeakub Ali', title: 'Assistant Professor' },
    { name: 'Md. Rakib Hossain', title: 'Assistant Professor' },
    { name: 'Shuvra Prokash Biswas', title: 'Assistant Professor' },
    { name: 'Hasan Sarker', title: 'Assistant Professor' },
    { name: 'Farzana Akter', title: 'Assistant Professor' },
    { name: 'Md Abu Ismail Siddique', title: 'Assistant Professor' },
    { name: 'Sharaf Tasnim', title: 'Assistant Professor' },
    { name: 'Md. Mahmudul Hasan', title: 'Lecturer' },
    { name: 'Md. Rakibul Islam', title: 'Lecturer' },
    { name: 'Md. Tarek Hassan', title: 'Lecturer' },
    { name: 'Mohammed Nazmul Islam Nahin', title: 'Lecturer' },
    { name: 'Rubaeat Ahammed', title: 'Lecturer' },
    { name: 'Rifa Tabassum Mim', title: 'Lecturer' },
  ];
  const RANK_ORDER = ['Professor', 'Associate Professor', 'Assistant Professor', 'Lecturer'];
  const teacherInput = $('#in-teacher'), teacherList = $('#teacherList');
  let comboMatches = [], comboActive = -1;
  const norm = s => String(s || '').toLowerCase().replace(/\./g, '');
  // fuzzy score: exact > prefix > substring > ordered-subsequence; -1 = no match
  function fuzzyScore(q, target){
    q = norm(q).trim(); target = norm(target);
    if(!q) return 0;
    if(target === q) return 1e6;
    if(target.startsWith(q)) return 1e5 - target.length;
    const sub = target.indexOf(q);
    if(sub !== -1) return 1e4 - sub * 10 - target.length;
    let qi = 0, score = 0, consec = 0, lastPos = -2;
    for(let i = 0; i < target.length && qi < q.length; i++){
      if(target[i] === ' ' && q[qi] !== ' ') continue;
      if(target[i] === q[qi]){
        qi++;
        consec = (i === lastPos + 1) ? consec + 1 : 1;
        score += 10 + consec * 5 + (i < 8 ? 3 : 0);
        lastPos = i;
      }
    }
    return qi === q.length ? score : -1;
  }
  // ---- combobox UI helpers : match highlight, avatars, floating panel ----
  function escHtml(s){ return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
  // normalized string + map back to original indices (dots are skipped in matching)
  function normIdx(s){
    const str = [], idx = [], lower = String(s || '').toLowerCase();
    for(let i = 0; i < lower.length; i++){
      if(lower[i] === '.') continue;
      str.push(lower[i]); idx.push(i);
    }
    return { str: str.join(''), idx };
  }
  // wrap query-matched chars of target in <mark> (contiguous preferred, else subsequence)
  function highlight(target, q){
    target = String(target ?? '');
    const t = normIdx(target), qq = normIdx(q).str.trim();
    if(!qq) return escHtml(target);
    let hits = null;
    const pos = t.str.indexOf(qq);
    if(pos !== -1){
      hits = new Set();
      for(let i = pos; i < pos + qq.length; i++) hits.add(t.idx[i]);
    } else {
      hits = new Set();
      let qi = 0;
      for(let i = 0; i < t.str.length && qi < qq.length; i++){
        if(t.str[i] === qq[qi]){ hits.add(t.idx[i]); qi++; }
      }
      if(qi !== qq.length) return escHtml(target);
    }
    let out = '';
    for(let i = 0; i < target.length; i++){
      out += hits.has(i) ? '<mark>' + escHtml(target[i]) + '</mark>' : escHtml(target[i]);
    }
    return out;
  }
  const AVATAR_COLORS = [['#ccfbf1', '#0f766e'], ['#dbeafe', '#1d4ed8'], ['#ede9fe', '#6d28d9'], ['#fef3c7', '#92400e'], ['#fce7f3', '#9d174d']];
  function avatarColor(key){
    let h = 0;
    for(const ch of String(key || '')){ h = (h * 31 + ch.charCodeAt(0)) >>> 0; }
    return AVATAR_COLORS[h % AVATAR_COLORS.length];
  }
  function initials(name){
    const words = String(name || '').replace(/\./g, ' ').split(/\s+/).filter(Boolean);
    if(!words.length) return '?';
    return ((words[0][0] || '') + (words.length > 1 ? (words[words.length - 1][0] || '') : '')).toUpperCase();
  }
  const DEPT_COLORS = { ETE: ['#ccfbf1', '#0f766e'], CSE: ['#dbeafe', '#1e40af'], EEE: ['#fef3c7', '#92400e'], Phy: ['#ede9fe', '#6d28d9'], Hum: ['#fce7f3', '#9d174d'] };
  function deptColor(dept){ return DEPT_COLORS[dept] || ['#f1f5f9', '#475569']; }
  function comboEmptyHTML(){
    return '<span class="t-name">No matches found</span><span class="t-title">Your custom text will be kept.</span>';
  }
  function comboHintHTML(){ return '<b>&uarr;&darr;</b> navigate &nbsp;&middot;&nbsp; <b>Enter</b> select &nbsp;&middot;&nbsp; <b>Esc</b> close'; }
  function paintHint(list){
    const hint = document.createElement('li');
    hint.className = 'combo-hint';
    hint.innerHTML = comboHintHTML();
    list.appendChild(hint);
  }
  // glue a list under its input with position:fixed (moved to <body> so cards never clip it)
  function floatCombo(input, list){
    if(list.parentElement !== document.body){ document.body.appendChild(list); list.classList.add('combo-float'); }
    list._comboInput = input;
    const r = input.getBoundingClientRect();
    const width = Math.max(240, Math.min(360, r.width, window.innerWidth - 16));
    list.style.width = width + 'px';
    list.style.left = Math.max(8, Math.min(r.left, window.innerWidth - width - 8)) + 'px';
    const want = Math.min(300, list.scrollHeight || 260);
    let top = r.bottom + 6, maxH = window.innerHeight - top - 8;
    if(maxH < 140){ top = Math.max(8, r.top - want - 6); maxH = r.top - top - 6; }
    list.style.top = Math.max(8, top) + 'px';
    list.style.maxHeight = Math.max(120, Math.min(300, maxH)) + 'px';
  }
  function refloatAll(){
    document.querySelectorAll('.combo-list:not([hidden])').forEach(l => { if(l._comboInput) floatCombo(l._comboInput, l); });
  }
  window.addEventListener('resize', refloatAll);
  document.addEventListener('scroll', ()=>{ requestAnimationFrame(refloatAll); }, true);
  function searchFaculty(q){
    q = String(q || '').trim();
    if(!q) return FACULTY.slice();
    return FACULTY
      .map(f => ({ f, s: Math.max(fuzzyScore(q, f.name), fuzzyScore(q, f.title) > 0 ? 1 : -1) }))
      .filter(r => r.s >= 0)
      .sort((a, b) => b.s - a.s)
      .map(r => r.f);
  }
  function paintCombo(){
    const q = teacherInput.value;
    teacherList.innerHTML = '';
    if(!comboMatches.length){
      const li = document.createElement('li');
      li.className = 'combo-empty';
      li.innerHTML = comboEmptyHTML();
      teacherList.appendChild(li);
    } else {
      let idx = 0;
      for(const rank of RANK_ORDER){
        const group = comboMatches.filter(f => f.title === rank);
        if(!group.length) continue;
        const head = document.createElement('li');
        head.className = 'combo-group';
        head.textContent = rank + ' · ' + group.length;
        teacherList.appendChild(head);
        for(const f of group){
          const li = document.createElement('li');
          li.setAttribute('data-idx', String(idx));
          li.setAttribute('role', 'option');
          if(idx === comboActive) li.classList.add('active');
          const [bg, fg] = avatarColor(f.name);
          const av = document.createElement('span');
          av.className = 't-avatar'; av.textContent = initials(f.name);
          av.style.background = bg; av.style.color = fg;
          const tx = document.createElement('span');
          tx.className = 't-text';
          const nm = document.createElement('span');
          nm.className = 't-name'; nm.innerHTML = highlight(f.name, q); nm.title = f.name;
          const tt = document.createElement('span');
          tt.className = 't-title'; tt.innerHTML = highlight(f.title, q);
          tx.appendChild(nm); tx.appendChild(tt);
          li.appendChild(av); li.appendChild(tx);
          li.addEventListener('mousedown', (e)=>{ e.preventDefault(); pickFaculty(f); });
          teacherList.appendChild(li);
          idx++;
        }
      }
      paintHint(teacherList);
    }
    const el = teacherList.querySelector('li[data-idx="' + comboActive + '"]');
    if(el) el.scrollIntoView({ block: 'nearest' });
  }
  function openCombo(){
    comboMatches = searchFaculty(teacherInput.value);
    comboActive = comboMatches.length ? 0 : -1;
    teacherList.hidden = false;
    paintCombo();
    floatCombo(teacherInput, teacherList);
    teacherInput.setAttribute('aria-expanded', 'true');
  }
  function closeCombo(){
    teacherList.hidden = true;
    teacherInput.setAttribute('aria-expanded', 'false');
    comboActive = -1;
  }
  function flatCount(){ return comboMatches.length; }
  function pickFaculty(f){
    teacherInput.value = f.name;
    const desig = document.querySelector('[data-bind="desig"]');
    if(desig) desig.value = f.title;
    closeCombo();
    render();
    saveSoon();
    requestAnimationFrame(updateScale);
    flash(f.name + ' — ' + f.title);
  }
  if(teacherInput && teacherList){
    teacherInput.addEventListener('focus', openCombo);
    teacherInput.addEventListener('input', ()=>{
      if(teacherList.hidden) openCombo();
      else { comboMatches = searchFaculty(teacherInput.value); comboActive = comboMatches.length ? 0 : -1; paintCombo(); }
    });
    teacherInput.addEventListener('keydown', (e)=>{
      if(teacherList.hidden) return;
      if(e.key === 'ArrowDown'){ e.preventDefault(); if(flatCount()){ comboActive = (comboActive + 1) % flatCount(); paintCombo(); } }
      else if(e.key === 'ArrowUp'){ e.preventDefault(); if(flatCount()){ comboActive = (comboActive - 1 + flatCount()) % flatCount(); paintCombo(); } }
      else if(e.key === 'Enter'){ if(comboActive >= 0 && comboMatches[comboActive]){ e.preventDefault(); pickFaculty(comboMatches[comboActive]); } else closeCombo(); }
      else if(e.key === 'Escape'){ e.preventDefault(); closeCombo(); }
    });
    teacherInput.addEventListener('blur', ()=>{ setTimeout(closeCombo, 120); });
    document.addEventListener('click', (e)=>{
      if(teacherList.hidden || !e.target.closest) return;
      const inCombo = document.getElementById('teacherCombo').contains(e.target) || e.target.closest('#teacherList');
      if(!inCombo) closeCombo();
    });
  }
  // ---- course Comboboxes : code + title share one sessional-course list ----
  const COURSES = [
    // 1st Year 1st Semester
    { code: 'ETE 1110', title: 'Engineering Graphics and Design', sem: '1st Year 1st Semester' },
    { code: 'ETE 1112', title: 'Sessional Based on ETE 1111', sem: '1st Year 1st Semester' },
    { code: 'ETE 1114', title: 'Sessional Based on ETE 1113', sem: '1st Year 1st Semester' },
    { code: 'Phy 1116', title: 'Sessional Based on Phy 1115', sem: '1st Year 1st Semester' },
    { code: 'Hum 1116', title: 'English Language Lab', sem: '1st Year 1st Semester' },
    // 1st Year 2nd Semester
    { code: 'ETE 1212', title: 'Sessional Based on ETE 1211', sem: '1st Year 2nd Semester' },
    { code: 'ETE 1214', title: 'Sessional Based on ETE 1213', sem: '1st Year 2nd Semester' },
    { code: 'CSE 1254', title: 'Object Oriented Programming Lab', sem: '1st Year 2nd Semester' },
    { code: 'EEE 1254', title: 'Sessional Based on EEE 1253', sem: '1st Year 2nd Semester' },
    // 2nd Year 1st Semester
    { code: 'ETE 2110', title: 'Electronic Circuit Design and Simulation Lab', sem: '2nd Year 1st Semester' },
    { code: 'ETE 2112', title: 'Sessional Based on ETE 2111', sem: '2nd Year 1st Semester' },
    { code: 'ETE 2114', title: 'Sessional Based on ETE 2113', sem: '2nd Year 1st Semester' },
    { code: 'ETE 2116', title: 'Sessional Based on ETE 2115', sem: '2nd Year 1st Semester' },
    { code: 'CSE 2154', title: 'Sessional Based on CSE 2153', sem: '2nd Year 1st Semester' },
    // 2nd Year 2nd Semester
    { code: 'ETE 2212', title: 'Sessional Based on ETE 2211', sem: '2nd Year 2nd Semester' },
    { code: 'CSE 2254', title: 'Sessional Based on CSE 2253', sem: '2nd Year 2nd Semester' },
    // 3rd Year 1st Semester
    { code: 'ETE 3112', title: 'Sessional Based on ETE 3111', sem: '3rd Year 1st Semester' },
    { code: 'ETE 3114', title: 'Sessional Based on ETE 3113', sem: '3rd Year 1st Semester' },
    { code: 'ETE 3116', title: 'Sessional Based on ETE 3115', sem: '3rd Year 1st Semester' },
    { code: 'ETE 3118', title: 'Sessional Based on ETE 3117', sem: '3rd Year 1st Semester' },
    { code: 'EEE 3154', title: 'Sessional Based on EEE 3153', sem: '3rd Year 1st Semester' },
    { code: 'CSE 3154', title: 'Web Programming', sem: '3rd Year 1st Semester' },
    // 3rd Year 2nd Semester
    { code: 'ETE 3212', title: 'Sessional Based on ETE 3211', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3214', title: 'Sessional Based on ETE 3213', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3216', title: 'Sessional Based on ETE 3215', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3220', title: 'Seminar', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3222', title: 'Sessional Based on ETE 3221', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3224', title: 'Sessional Based on ETE 3223', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3226', title: 'Sessional Based on ETE 3225', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3228', title: 'Sessional Based on ETE 3227', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3230', title: 'Sessional Based on ETE 3229', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3232', title: 'Sessional Based on ETE 3231', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3234', title: 'Sessional Based on ETE 3233', sem: '3rd Year 2nd Semester' },
    { code: 'ETE 3236', title: 'Sessional Based on ETE 3235', sem: '3rd Year 2nd Semester' },
    // 4th Year 1st Semester
    { code: 'ETE 4112', title: 'Sessional Based on ETE 4111', sem: '4th Year 1st Semester' },
    { code: 'ETE 4114', title: 'Sessional Based on ETE 4113', sem: '4th Year 1st Semester' },
    { code: 'ETE 4116', title: 'Sessional Based on ETE 4115', sem: '4th Year 1st Semester' },
    { code: 'ETE 4118', title: 'Sessional Based on ETE 4117', sem: '4th Year 1st Semester' },
    { code: 'ETE 4120', title: 'Industrial Training', sem: '4th Year 1st Semester' },
    { code: 'ETE 4122', title: 'Sessional Based on ETE 4121', sem: '4th Year 1st Semester' },
    { code: 'ETE 4124', title: 'Sessional Based on ETE 4123', sem: '4th Year 1st Semester' },
    { code: 'ETE 4126', title: 'Sessional Based on ETE 4125', sem: '4th Year 1st Semester' },
    { code: 'ETE 4128', title: 'Sessional Based on ETE 4127', sem: '4th Year 1st Semester' },
    { code: 'ETE 4130', title: 'Sessional Based on ETE 4129', sem: '4th Year 1st Semester' },
    { code: 'ETE 4132', title: 'Sessional Based on ETE 4131', sem: '4th Year 1st Semester' },
    { code: 'ETE 4134', title: 'Sessional Based on ETE 4133', sem: '4th Year 1st Semester' },
    { code: 'ETE 4136', title: 'Sessional Based on ETE 4135', sem: '4th Year 1st Semester' },
    { code: 'ETE 4138', title: 'Sessional Based on ETE 4137', sem: '4th Year 1st Semester' },
    { code: 'ETE 4140', title: 'Sessional Based on ETE 4139', sem: '4th Year 1st Semester' },
    // 4th Year 2nd Semester
    { code: 'ETE 4200', title: 'Project & Thesis (Part III)', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4212', title: 'Sessional Based on ETE 4211', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4214', title: 'Sessional Based on ETE 4213', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4216', title: 'Sessional Based on ETE 4215', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4218', title: 'Sessional Based on ETE 4217', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4220', title: 'Sessional Based on ETE 4219', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4222', title: 'Sessional Based on ETE 4221', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4224', title: 'Sessional Based on ETE 4223', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4226', title: 'Sessional Based on ETE 4225', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4228', title: 'Sessional Based on ETE 4227', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4230', title: 'Sessional Based on ETE 4229', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4232', title: 'Sessional Based on ETE 4231', sem: '4th Year 2nd Semester' },
    { code: 'ETE 4234', title: 'Sessional Based on ETE 4233', sem: '4th Year 2nd Semester' },
  ];
  const SEM_ORDER = ['1st Year 1st Semester', '1st Year 2nd Semester', '2nd Year 1st Semester', '2nd Year 2nd Semester', '3rd Year 1st Semester', '3rd Year 2nd Semester', '4th Year 1st Semester', '4th Year 2nd Semester'];
  // primary field (the box being typed in) scores double; both fields match
  function searchCourses(q, primary){
    q = String(q || '').trim();
    if(!q) return COURSES.slice();
    return COURSES
      .map(c => ({ c, s: Math.max(fuzzyScore(q, primary === 'code' ? c.code : c.title) * 2, fuzzyScore(q, primary === 'code' ? c.title : c.code)) }))
      .filter(r => r.s >= 0)
      .sort((a, b) => b.s - a.s)
      .map(r => r.c);
  }
  function pickCourse(c){
    const codeIn = document.querySelector('[data-bind="courseCode"]');
    const titleIn = document.querySelector('[data-bind="courseTitle"]');
    if(codeIn) codeIn.value = c.code;
    if(titleIn) titleIn.value = c.title;
    $$('.combo-list').forEach(l => { l.hidden = true; });
    render();
    saveSoon();
    requestAnimationFrame(updateScale);
    flash(c.code + ' — ' + c.title);
  }
  function makeCourseCombo(inputId, listId, primary){
    const input = document.getElementById(inputId), list = document.getElementById(listId);
    if(!input || !list) return;
    let matches = [], active = -1;
    function paint(){
      const q = input.value;
      list.innerHTML = '';
      if(!matches.length){
        const li = document.createElement('li');
        li.className = 'combo-empty';
        li.innerHTML = comboEmptyHTML();
        list.appendChild(li);
      } else {
        let idx = 0;
        for(const sem of SEM_ORDER){
          const group = matches.filter(c => c.sem === sem);
          if(!group.length) continue;
          const head = document.createElement('li');
          head.className = 'combo-group';
          head.textContent = sem + ' · ' + group.length;
          list.appendChild(head);
          for(const c of group){
            const li = document.createElement('li');
            li.setAttribute('data-idx', String(idx));
            li.setAttribute('role', 'option');
            if(idx === active) li.classList.add('active');
            const dept = String(c.code).split(' ')[0];
            const [bg, fg] = deptColor(dept);
            const badge = document.createElement('span');
            badge.className = 't-badge'; badge.textContent = dept;
            badge.style.background = bg; badge.style.color = fg;
            const tx = document.createElement('span');
            tx.className = 't-text';
            const cd = document.createElement('span');
            cd.className = 't-name'; cd.innerHTML = highlight(c.code, q);
            cd.title = c.code + ' — ' + c.title;
            const tt = document.createElement('span');
            tt.className = 't-title'; tt.innerHTML = highlight(c.title, q);
            tt.title = c.title;
            tx.appendChild(cd); tx.appendChild(tt);
            li.appendChild(badge); li.appendChild(tx);
            li.addEventListener('mousedown', (e)=>{ e.preventDefault(); pickCourse(c); });
            list.appendChild(li);
            idx++;
          }
        }
        paintHint(list);
      }
      const el = list.querySelector('li[data-idx="' + active + '"]');
      if(el) el.scrollIntoView({ block: 'nearest' });
    }
    function open(){
      $$('.combo-list').forEach(l => { if(l !== list) l.hidden = true; });
      matches = searchCourses(input.value, primary);
      active = matches.length ? 0 : -1;
      list.hidden = false;
      paint();
      floatCombo(input, list);
      input.setAttribute('aria-expanded', 'true');
    }
    function close(){
      list.hidden = true;
      input.setAttribute('aria-expanded', 'false');
      active = -1;
    }
    input.addEventListener('focus', open);
    input.addEventListener('input', ()=>{
      if(list.hidden) open();
      else { matches = searchCourses(input.value, primary); active = matches.length ? 0 : -1; paint(); }
    });
    input.addEventListener('keydown', (e)=>{
      if(list.hidden) return;
      if(e.key === 'ArrowDown'){ e.preventDefault(); if(matches.length){ active = (active + 1) % matches.length; paint(); } }
      else if(e.key === 'ArrowUp'){ e.preventDefault(); if(matches.length){ active = (active - 1 + matches.length) % matches.length; paint(); } }
      else if(e.key === 'Enter'){ if(active >= 0 && matches[active]){ e.preventDefault(); pickCourse(matches[active]); } else close(); }
      else if(e.key === 'Escape'){ e.preventDefault(); close(); }
    });
    input.addEventListener('blur', ()=>{ setTimeout(close, 120); });
  }
  makeCourseCombo('in-courseCode', 'courseList', 'code');
  makeCourseCombo('in-courseTitle', 'titleList', 'title');
  document.addEventListener('click', (e)=>{
    if(!e.target.closest || e.target.closest('#courseCombo') || e.target.closest('#titleCombo') || e.target.closest('#courseList') || e.target.closest('#titleList')) return;
    ['courseList', 'titleList'].forEach(id => { const l = document.getElementById(id); if(l) l.hidden = true; });
  });
  // ---- persistence : last edited state autosaved to localStorage ----
  const LS_KEY = 'ruetlatex-state-v2';
  const LS_KEY_OLD = 'ruetlatex-state-v1'; // stale key holding pre-generic defaults; never read, cleaned once
  const CHECK_IDS = ['showPoor','upperRule','lowerRule','bottomRule'];
  function collectPersist(){
    const binds = {};
    $$('[data-bind]').forEach(el=>{ binds[el.dataset.bind] = el.value; });
    const checks = {};
    CHECK_IDS.forEach(id=>{ const c = document.getElementById(id); if(c) checks[id] = c.checked; });
    // NOTE: custom Google Fonts are deliberately session-only — nothing about
    // them (URL, name, injected link) is persisted, so they vanish on reload.
    const DEFAULT_FONT = "'Palatino Nova', 'Book Antiqua', serif";
    return {
      v: 2,
      binds,
      font: fontSelect.value === 'custom' ? DEFAULT_FONT : fontSelect.value,
      baseSize: $('#baseSize').value, baseSizeCustom: $('#baseSizeCustom').value,
      lineSpacing: $('#lineSpacing').value, lineSpacingCustom: $('#lineSpacingCustom').value,
      ruleThick: $('#ruleThick').value, ruleGap: $('#ruleGap').value,
      logoWidth: $('#logoWidth').value, logoPos: $('#logoPos').value,
      checks,
      tapEdit: isTapOn(),
      markingOpen: !!markingToggle.checked,
      fmt: fmtState,
      marks: $$('#sheet .marks li').map(li=>li.innerHTML)
    };
  }
  let saveT = null;
  let resetting = false; // set when Reset is clicked so unload handlers can't re-save
  function saveNow(){
    if(resetting) return;
    try{
      localStorage.setItem(LS_KEY, JSON.stringify(collectPersist()));
      localStorage.removeItem(LS_KEY_OLD); // one-time cleanup of stale pre-generic state
    }catch(e){/* quota/private mode */}
  }
  function saveSoon(){
    if(resetting) return;
    clearTimeout(saveT); saveT = setTimeout(saveNow, 400);
  }
  function fire(el, type){ el.dispatchEvent(new Event(type, {bubbles:true})); }
  function restorePersist(){
    let s = null;
    try{ s = JSON.parse(localStorage.getItem(LS_KEY) || 'null'); }catch(e){ s = null; }
    if(!s || s.v !== 2) return false;
    // text fields
    $$('[data-bind]').forEach(el=>{ if(s.binds && s.binds[el.dataset.bind] != null) el.value = s.binds[el.dataset.bind]; });
    // selects / ranges (custom size/spacing values restored into their inputs)
    if(s.baseSize === 'custom'){
      $('#baseSize').value = 'custom';
      if(s.baseSizeCustom) $('#baseSizeCustom').value = s.baseSizeCustom;
    } else if(s.baseSize) $('#baseSize').value = s.baseSize;
    if(s.lineSpacing === 'custom'){
      $('#lineSpacing').value = 'custom';
      if(s.lineSpacingCustom) $('#lineSpacingCustom').value = s.lineSpacingCustom;
    } else if(s.lineSpacing) $('#lineSpacing').value = s.lineSpacing;
    if(s.ruleThick) $('#ruleThick').value = s.ruleThick;
    if(s.ruleGap) $('#ruleGap').value = s.ruleGap;
    if(s.logoWidth) $('#logoWidth').value = s.logoWidth;
    if(s.logoPos != null) $('#logoPos').value = s.logoPos;
    // checkboxes
    CHECK_IDS.forEach(id=>{ const c = document.getElementById(id); if(c && s.checks && s.checks[id] != null) c.checked = !!s.checks[id]; });
    // custom Google Fonts are session-only: any previously saved custom state
    // (e.g. a one-time Garamond) is ignored so it is gone on reopen.
    // migrate pre-rename saved fonts to the new native families
    let savedFont = s.font;
    if(!savedFont || savedFont === 'custom') savedFont = "'Palatino Nova', 'Book Antiqua', serif";
    if(savedFont && savedFont.indexOf('Georgia') !== -1) savedFont = "'Times New Roman', Times, serif";
    if(savedFont && savedFont.indexOf('Noto Serif') !== -1) savedFont = "'Droid Serif', serif";
    if(savedFont && savedFont.indexOf('Palatino RUET') !== -1) savedFont = "'Palatino Nova', 'Book Antiqua', serif";
    if(savedFont && (fontSelect.querySelector('option[value="' + savedFont + '"]') || savedFont === 'custom')) fontSelect.value = savedFont;
    // rich-text + marking rows
    if(s.fmt) Object.assign(fmtState, s.fmt);
    if(Array.isArray(s.marks)){
      $$('#sheet .marks li').forEach((li,i)=>{ if(s.marks[i] != null) li.innerHTML = s.marks[i]; });
    }
    // re-apply visuals through the real handlers
    fire(fontSelect, 'change');
    fire($('#baseSize'), 'change'); fire($('#lineSpacing'), 'change');
    fire($('#logoWidth'), 'input');
    fire($('#logoPos'), 'input');
    fire($('#ruleThick'), 'change'); fire($('#ruleGap'), 'change');
    fire($('#showPoor'), 'change');
    ['upperRule','lowerRule','bottomRule'].forEach(id=>fire(document.getElementById(id), 'change'));
    tapToggle.checked = !!s.tapEdit;
    applyTap();
    markingToggle.checked = !!s.markingOpen;
    applyMarking();
    return true;
  }
  document.addEventListener('input', saveSoon);
  document.addEventListener('change', saveSoon);
  window.addEventListener('beforeunload', saveNow);

  $('#resetBtn').addEventListener('click', ()=>{
    // truly wipe everything: block any pending/deferred saves (incl. beforeunload),
    // clear storage, then reload to pristine defaults
    resetting = true;
    clearTimeout(saveT);
    try{ localStorage.removeItem(LS_KEY); localStorage.removeItem(LS_KEY_OLD); }catch(e){}
    location.reload();
  });

  // ---- windowless autofit (compare.html style): real-size A4, scale to column width ----
  const PAGE_W = 210 * 3.7795275591; // 794px @96dpi
  function updateScale(){
    const w = stage.clientWidth;
    if(!w) return;
    const s = Math.min(1, w / PAGE_W);
    scaler.style.transform = 'scale(' + s + ')';
    scaler.style.width = (PAGE_W * s) + 'px';
    scaler.style.height = (1122.5 * s) + 'px';
  }
  window.addEventListener('resize', ()=>requestAnimationFrame(updateScale));
  if('ResizeObserver' in window) new ResizeObserver(()=>requestAnimationFrame(updateScale)).observe(stage);
  if(document.fonts && document.fonts.ready) document.fonts.ready.then(()=>updateScale());

  // live binding
  $$('[data-bind]').forEach(el=>{
    el.addEventListener('input', ()=>{ render(); requestAnimationFrame(updateScale); });
  });

  // ---- TEX buttons ----
  function download(name, text, type){
    const a=document.createElement('a');
    a.href=URL.createObjectURL(new Blob([text],{type:type||'text/plain'})); a.download=name; a.click();
    setTimeout(()=>URL.revokeObjectURL(a.href),2000);
  }
  $('#texCopy').onclick = async ()=>{
    try{ await navigator.clipboard.writeText($('#texCode').textContent); flash('LaTeX copied — paste into Overleaf'); }
    catch{ flash('Copy blocked — select the code manually'); }
  };
  $('#texDownload').onclick = ()=>{ download('ruet-cover.tex', $('#texCode').textContent, 'text/x-tex'); flash('.tex downloaded'); };

  // ---- print preview : browser dialog (Save as PDF / printer) ----
  function doPrint(){
    $$('.combo-list').forEach(l => { l.hidden = true; });
    render();
    const root = $('#printRoot');
    root.innerHTML='';
    const clone = sheet.cloneNode(true);
    clone.removeAttribute('id');
    clone.style.transform='none';
    clone.style.fontFamily = getComputedStyle(sheet).fontFamily;
    clone.style.width='210mm'; clone.style.height='297mm'; clone.style.overflow='hidden';
    root.appendChild(clone);
    window.print();
  }
  $('#topPrintBtn').onclick = doPrint;

  // ---- one-click PDF : lossless PNG of the exact sheet → A4 download ----
  // http(s): html-to-image (SVG serialization, embeds webfonts).
  // file://: html-to-image cannot fetch() local assets (Chrome blocks
  // file:// fetches → CORS), so we rasterize with html2canvas instead —
  // canvas text uses the already-loaded document fonts and the logo loads
  // via <img>, neither of which needs fetch.
  function loadScript(src, test){
    if(test()) return Promise.resolve();
    return new Promise((res, rej)=>{
      const s = document.createElement('script');
      s.src = src;
      s.onload = ()=>res();
      s.onerror = rej;
      document.head.appendChild(s);
    });
  }
  async function rasterizeFile(pr){
    // html2canvas blanks on transformed/clipped content: briefly show the
    // sheet at full size, unscaled and scrolled into view, then restore.
    const prevT = scaler.style.transform, prevW = scaler.style.width, prevH = scaler.style.height;
    const prevX = window.scrollX, prevY = window.scrollY;
    scaler.style.transform = 'none'; scaler.style.width = ''; scaler.style.height = '';
    sheet.scrollIntoView({ block: 'start', inline: 'nearest' });
    await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
    try{
      const canvas = await window.html2canvas(sheet, { backgroundColor: '#ffffff', scale: pr, logging: false, useCORS: false });
      return canvas.toDataURL('image/png');
    } finally {
      scaler.style.transform = prevT; scaler.style.width = prevW; scaler.style.height = prevH;
      window.scrollTo(prevX, prevY);
      requestAnimationFrame(updateScale);
    }
  }
  async function downloadPDF(){
    flash('Rendering PDF…');
    try{
      // file:// cannot fetch() local assets, which html-to-image requires.
      const fileMode = location.protocol === 'file:';
      if(fileMode){
        await loadScript(
          'https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js',
          ()=>!!window.html2canvas
        );
      } else {
        await loadScript(
          'https://cdnjs.cloudflare.com/ajax/libs/html-to-image/1.11.11/html-to-image.min.js',
          ()=>!!window.htmlToImage
        );
      }
      await loadScript(
        'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js',
        ()=>!!(window.jspdf && window.jspdf.jsPDF)
      );
      // --- wait for the ACTIVE webfonts (all 4 faces) so the snapshot
      // never catches a fallback / faux-bold frame ---
      try{
        if(document.fonts && document.fonts.ready){
          const fam = getComputedStyle(sheet).fontFamily || '';
          const m = fam.match(/'([^']+)'/) || fam.match(/"([^"]+)"/);
          const active = m ? m[1] : 'Palatino Nova';
          await Promise.all([
            document.fonts.load('400 16px "' + active + '"'),
            document.fonts.load('700 16px "' + active + '"'),
            document.fonts.load('italic 400 16px "' + active + '"'),
            document.fonts.load('italic 700 16px "' + active + '"'),
          ]).catch(()=>{});
          await document.fonts.ready;
        }
      }catch(e){/* non-fatal */}
      if(document.activeElement) document.activeElement.blur();
      hideToolbar();
      $$('.combo-list').forEach(l => { l.hidden = true; });
      render();
      await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
      // HIGH-DPI raster: A4 @96dpi is 794x1123px. PNG is lossless; JPEG chroma
      // subsampling was smudging glyph edges, so never use JPEG.
      const W = sheet.scrollWidth || sheet.offsetWidth;
      const H = sheet.scrollHeight || sheet.offsetHeight;
      const HI_DPI = 5, FALLBACK_DPI = 3;
      let dataUrl = null;
      if(fileMode){
        // ~384 DPI via canvas; retry smaller if the device runs out of memory
        try{
          dataUrl = await rasterizeFile(4);
        }catch(e){
          console.warn('file-mode snapshot failed, retrying smaller', e);
          dataUrl = await rasterizeFile(2);
        }
      } else {
        // ~480 DPI via SVG serialization
        const snapOpts = (pr)=>({
          cacheBust: false, backgroundColor: '#ffffff',
          width: W, height: H,
          canvasWidth: Math.round(W * pr), canvasHeight: Math.round(H * pr),
          pixelRatio: 1, // size already baked into canvasWidth/Height; avoids double-scale blur
          skipAutoScale: true,
          style: { transform: 'none', margin: '0' },
        });
        try{
          dataUrl = await window.htmlToImage.toPng(sheet, snapOpts(HI_DPI));
        }catch(e){
          console.warn('hi-dpi snapshot failed, retrying at standard dpi', e);
          dataUrl = await window.htmlToImage.toPng(sheet, snapOpts(FALLBACK_DPI));
        }
      }
      const JST = window.jspdf.jsPDF;
      const pdf = new JST({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      // 'FAST' = Flate-compress the raster. Without it jsPDF embeds raw RGBA
      // (~89MB at 5x — hangs/fails the download); with it ~0.7MB, still lossless.
      pdf.addImage(dataUrl, 'PNG', 0, 0, 210, 297, undefined, 'FAST');
      const expNo = ((state.expNo || '01') + '').trim() || '01';
      // filename: CourseCode_TeacherName_ExpNo.pdf (filesystem-safe)
      const cleanName = s => String(s ?? '').trim().replace(/[\\/:*?"<>|]/g, '').replace(/\s+/g, ' ').trim();
      const coursePart = cleanName(state.courseCode || defaults.courseCode) || 'Course';
      const teacherPart = cleanName(state.teacher || defaults.teacher) || 'Teacher';
      const expPart = cleanName(expNo) || '01';
      // own attached anchor instead of pdf.save(): the bundled FileSaver
      // dispatches on a detached anchor, which browsers may silently drop.
      const pdfBlob = pdf.output('blob');
      const pdfUrl = URL.createObjectURL(pdfBlob);
      const dl = document.createElement('a');
      dl.href = pdfUrl;
      dl.download = coursePart + '_' + teacherPart + '_' + expPart + '.pdf';
      document.body.appendChild(dl);
      dl.click();
      setTimeout(()=>{ URL.revokeObjectURL(pdfUrl); dl.remove(); }, 4000);
      flash('PDF downloaded');
    }catch(err){
      console.error(err);
      flash('Direct PDF failed — opened print instead');
      doPrint();
    }
  }
  $('#topPdfBtn').onclick = downloadPDF;
  const navPdfBtn = $('#navPdfBtn');
  if(navPdfBtn) navPdfBtn.onclick = downloadPDF; // mobile navbar shortcut, same action

  // ---- responsive nav : hamburger menu with links + actions ----
  const ham = $('#hamburger'), links = $('#navLinks');
  function setMenu(open){
    links.classList.toggle('open', open);
    ham.classList.toggle('active', open);
    ham.setAttribute('aria-expanded', String(open));
  }
  ham.addEventListener('click', (e)=>{
    e.stopPropagation();
    setMenu(!links.classList.contains('open'));
  });
  // close when a link or menu button is tapped (tap-toggle switches stay usable in-menu)
  $$('#navLinks a, #navLinks button:not(.tap-toggle)').forEach(el=>el.addEventListener('click', ()=>setMenu(false)));
  // close on outside tap
  document.addEventListener('click', (e)=>{
    if(links.classList.contains('open') && !links.contains(e.target) && !ham.contains(e.target)) setMenu(false);
  });
  // close on Escape
  document.addEventListener('keydown', (e)=>{ if(e.key==='Escape') setMenu(false); });
  // reset when resizing back to desktop
  window.addEventListener('resize', ()=>{ if(window.innerWidth > 1024) setMenu(false); });

  const restored = restorePersist();
  if(!restored){
    render();
    applyFontValue(fontSelect.value);
  } else {
    render(); // re-applies binds + stored rich-text, rebuilds .tex
    flash('Restored your last edits');
  }
  requestAnimationFrame(updateScale);
})();
